#!/usr/bin/env python3
"""Verify install-visible versioning and executable UI identity."""

import json
import plistlib
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]


def require(condition: bool, message: str) -> None:
    if not condition:
        raise SystemExit(f"FAIL: {message}")


def main() -> None:
    base = (ROOT / "Configuration/Base.xcconfig").read_text(encoding="utf-8")
    generated = (ROOT / "Configuration/BuildIdentity.generated.xcconfig").read_text(encoding="utf-8")
    build_identity = json.loads((ROOT / "Configuration/build-identity.json").read_text(encoding="utf-8"))
    plist = plistlib.loads((ROOT / "App/Info.plist").read_bytes())
    identity = (ROOT / "App/Build/VulpraBuildIdentity.swift").read_text(encoding="utf-8")
    validator = (ROOT / "Tools/Engine/validate-ipa.py").read_text(encoding="utf-8")
    workflow = (ROOT / ".github/workflows/build-ios-packages.yml").read_text(encoding="utf-8")
    lock = json.loads((ROOT / "Configuration/engine-artifact-lock.json").read_text(encoding="utf-8"))

    fingerprint = build_identity["uiFingerprint"]
    require('#include "BuildIdentity.generated.xcconfig"' in base,
            "Base.xcconfig does not consume generated identity")
    require(f"MARKETING_VERSION = {build_identity['marketingVersion']}" in generated,
            "generated marketing version is stale")
    require(f"CURRENT_PROJECT_VERSION = {build_identity['buildVersion']}" in generated,
            "generated build version is stale")
    require(plist.get("VulpraUIBuildFingerprint") == "$(VULPRA_UI_FINGERPRINT)",
            "Info.plist does not consume generated UI fingerprint")
    require(fingerprint in identity and "Generated by Tools/Build" in identity,
            "App executable identity source is not generated from the manifest")
    require("VulpraUIBuildFingerprint" in validator and "load_build_identity" in validator,
            "package validator does not enforce UI identity")
    require("generate-build-identity.py --print" in workflow,
            "package workflow duplicates build identity constants")
    require("engine-artifact-lock.json" in workflow,
            "package workflow does not enforce the repository artifact lock")
    simulator = (ROOT / ".github/workflows/simulator-smoke.yml").read_text(encoding="utf-8")
    require("App binaries do not contain the UI fingerprint" in simulator and
            "for path in app.iterdir()" in simulator,
            "simulator workflow does not account for Xcode debug dylib binaries")
    require("lock['simulator']['archive']" in simulator and "xcrun vtool" not in simulator,
            "simulator workflow does not use the repository simulator lock")
    require(lock.get("releaseTag") == "vulpra-engine-v4-candidate",
            "artifact lock release tag is wrong")
    device = lock.get("device", {})
    require(device.get("archiveSHA256") ==
            "9d62f558514f3749b93e8ee69d9063919c0545f7bc8f2a172024919b556bdcde",
            "device archive SHA-256 is not pinned")
    require(device.get("artifactId") ==
            "vulpra-gecko-ios-arm64-v4-fb98d5119a6c3e53ea96015a78a19269fef447a88fdf37a14b1bf0bc63e91ba9",
            "device artifact ID is not pinned")
    require(device.get("sourceCommit") == "27b462b22705a8860f7ab0d33aa5b4b658ae5932",
            "device source commit is not pinned")
    simulator_lock = lock.get("simulator", {})
    require(simulator_lock.get("archiveSHA256") ==
            "264cd55232440f3b0407acb2b8249f2adb7bba3dd8e480ebaac41db4fd39fa5f",
            "simulator archive SHA-256 is not pinned to the validated runtime")
    require(simulator_lock.get("artifactId") ==
            "vulpra-gecko-ios-simulator-arm64-v4-7b4c20887697b8bf5e99ba644aaf2ce0eb65c446d0f2a03d1600b4caf8883a56",
            "simulator content identity is not pinned")
    require(simulator_lock.get("abiVersion") == "firefox-152.0.6-ios-abi-1",
            "simulator ABI version is not pinned")
    require(simulator_lock.get("producerRun") == 30277909573 and
            simulator_lock.get("producerArtifactId") == 8663406576 and
            simulator_lock.get("producerArchiveSHA256") ==
            "3a391d55b80c7d148c8fb3f11f04f4308484278dcfd9451101ce95737808884b",
            "simulator producer is not traceable")
    require(simulator_lock.get("baselineArtifactId") ==
            "vulpra-gecko-ios-simulator-arm64-v4-532166d08ca95da9774b54dc50e1493d8fac52bc06ea80e4961711af0f9adbbf",
            "simulator inherited static-resource baseline is not traceable")
    require(simulator_lock.get("runtimePolicy") ==
            "force-software-webrender-on-coresimulator",
            "simulator renderer policy is not explicit")
    for token in (
        "ENGINE_ARTIFACT_ID",
        "ENGINE_ABI_VERSION",
        "force-software-webrender-on-coresimulator",
        'pref("gfx.webrender.software", true);',
    ):
        require(token in simulator,
                f"simulator workflow does not enforce locked runtime policy: {token}")

    print("PASS: package version, UI fingerprint, and artifact identity contracts")


if __name__ == "__main__":
    main()
