#!/usr/bin/env python3
"""Verify install-visible versioning and executable UI identity."""

import json
import plistlib
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]


def require(condition: bool, message: str) -> None:
    if not condition:
        raise SystemExit(f"FAIL: {message}")


def main() -> None:
    base = (ROOT / "Configuration/Base.xcconfig").read_text(encoding="utf-8")
    generated = (ROOT / "Configuration/BuildIdentity.generated.xcconfig").read_text(encoding="utf-8")
    build_identity = json.loads((ROOT / "Configuration/build-identity.json").read_text(encoding="utf-8"))
    plist = plistlib.loads((ROOT / "App/Info.plist").read_bytes())
    identity = (ROOT / "App/Build/VulpraBuildIdentity.swift").read_text(encoding="utf-8")
    validator = (ROOT / "Tools/Engine/validate-ipa.py").read_text(encoding="utf-8")
    workflow = (ROOT / ".github/workflows/build-ios-packages.yml").read_text(encoding="utf-8")
    lock = json.loads((ROOT / "Configuration/engine-artifact-lock.json").read_text(encoding="utf-8"))

    fingerprint = build_identity["uiFingerprint"]
    require('#include "BuildIdentity.generated.xcconfig"' in base,
            "Base.xcconfig does not consume generated identity")
    require(f"MARKETING_VERSION = {build_identity['marketingVersion']}" in generated,
            "generated marketing version is stale")
    require(f"CURRENT_PROJECT_VERSION = {build_identity['buildVersion']}" in generated,
            "generated build version is stale")
    require(plist.get("VulpraUIBuildFingerprint") == "$(VULPRA_UI_FINGERPRINT)",
            "Info.plist does not consume generated UI fingerprint")
    require(fingerprint in identity and "Generated by Tools/Build" in identity,
            "App executable identity source is not generated from the manifest")
    require("VulpraUIBuildFingerprint" in validator and "load_build_identity" in validator,
            "package validator does not enforce UI identity")
    require("generate-build-identity.py --print" in workflow,
            "package workflow duplicates build identity constants")
    require("engine-artifact-lock.json" in workflow,
            "package workflow does not enforce the repository artifact lock")
    simulator = (ROOT / ".github/workflows/simulator-smoke.yml").read_text(encoding="utf-8")
    require("App binaries do not contain the UI fingerprint" in simulator and
            "for path in app.iterdir()" in simulator,
            "simulator workflow does not account for Xcode debug dylib binaries")
    require("lock['simulator']['archive']" in simulator and "xcrun vtool" not in simulator,
            "simulator workflow does not use the repository simulator lock")
    require(lock.get("releaseTag") == "vulpra-engine-v4-candidate",
            "artifact lock release tag is wrong")
    device = lock.get("device", {})
    require(device.get("archiveSHA256") ==
            "9d62f558514f3749b93e8ee69d9063919c0545f7bc8f2a172024919b556bdcde",
            "device archive SHA-256 is not pinned")
    require(device.get("artifactId") ==
            "vulpra-gecko-ios-arm64-v4-fb98d5119a6c3e53ea96015a78a19269fef447a88fdf37a14b1bf0bc63e91ba9",
            "device artifact ID is not pinned")
    require(device.get("sourceCommit") == "27b462b22705a8860f7ab0d33aa5b4b658ae5932",
            "device source commit is not pinned")
    simulator_lock = lock.get("simulator", {})
    require(simulator_lock.get("archiveSHA256") ==
            "5f5f68d9ca9757348806ba2a8f67e39f836a9351105547ae5446720fdc616adc",
            "simulator archive SHA-256 is not pinned to the validated runtime")
    require(simulator_lock.get("artifactId") ==
            "vulpra-gecko-ios-simulator-arm64-v4-1789137b7a44f05988751fe76ecd9ed44016207bd1e34a39b3778283766e7d5d",
            "simulator content identity is not pinned")
    require(simulator_lock.get("abiVersion") == "firefox-152.0.6-ios-abi-1",
            "simulator ABI version is not pinned")
    require(simulator_lock.get("producerRunId") == 30361153382,
            "Simulator producer run is not pinned")
    require(simulator_lock.get("producerHeadSha") ==
            "a84e040fd4b5d811862c782faf674e5e478145d4",
            "Simulator producer snapshot is not pinned")
    require(simulator_lock.get("producedFromArtifactId") == device.get("artifactId"),
            "Simulator producer source artifact is not the verified device artifact")
    require(simulator_lock.get("producerTool") ==
            "Tools/Engine/produce-simulator-artifact.sh",
            "Simulator producer owner is not traceable")
    require(simulator_lock.get("producerPolicy") ==
            "apple-vtool-set-build-version-iossim-15",
            "Simulator producer policy is not explicit")
    require("derivedFromArtifactId" not in simulator_lock and
            "derivationTool" not in simulator_lock and
            "derivationPolicy" not in simulator_lock,
            "retired device-to-Simulator derivation remains in the lock")
    for token in (
        "ENGINE_ARTIFACT_ID",
        "ENGINE_ABI_VERSION",
        "ENGINE_PRODUCER_RUN_ID",
        "ENGINE_PRODUCED_FROM_ARTIFACT_ID",
        "apple-vtool-set-build-version-iossim-15",
    ):
        require(token in simulator,
                f"simulator workflow does not enforce locked runtime policy: {token}")

    print("PASS: package version, UI fingerprint, and artifact identity contracts")


if __name__ == "__main__":
    main()
